title: Rishabh's Blog
email: rishabhbohra01@gmail.com
#TODO
description: >- # this means to ignore newlines until "baseurl:" 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rishxbhbohra
github_username:  rishabh96b

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache

search: true
author:
  name: "Rishabh Bohra"
  avatar: "/assets/images/bio-img.jpeg"
  bio: "Software Engineer, Tinkerer, Internet Citizen and Traveller" # Note: Markdown is allowed
  location: "Internet"
  links:
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://rishabhbohra.me"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rishxbhbohra"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rishabh96b"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/rishabhxbohra"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
